version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "127.0.0.1:8086:8086"

volumes:
  grafana-data:
  influxdb-data: